baseURL = "https://nsidorenco.com/"
languageCode = "en-us"
title = "Nikolaj Sidorenco"
theme = ["github.com/ojroques/hugo-researcher"]
disableKinds = ["taxonomy", "term"]

[params]
  author = "Nikolaj Sidorenco"
  favicon = "favicon.ico"
  lang = "en"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "Github"
    url = "https://github.com/nsidorenco"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1
  [[menu.main]]
    name = "Contact"
    url  = "/contact"
    weight = 3
